version: 2.1

orbs:
  maven: circleci/maven@1.1.0

# workflows:
#   maven_test:
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.8-jdk
        auth:
            username: $DOCKERHUB_USER
            password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:latest
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD 
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: bookstore
          POSTGRES_PASSWORD: sqlpq
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: 
          name: Run Maven test
          command: |
            mvn clean install -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw
      

      


